### ISSUE TITLE
creating an variant type

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-cpp#40]
We need an variant object type to allow us to cast object to the correct object:

https://firebase.google.com/docs/reference/cpp/class/firebase/variant

**Comment by frobware** [comment]
mapbox variant example:

https://github.com/frobware/deepstream.io-client-cpp/tree/mapbox-variant

**Comment by frobware** [comment]
https://github.com/frobware/deepstream.io-client-cpp/tree/json-variant
