### ISSUE TITLE
connection: be able to connect using ssl

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-cpp#57]
We need to be able to provide `wss` as a protocol without having to pass in certificates.

Works:
``deepstream::Client client("ws://localhost:6020/deepstream");`

Should also work:
``deepstream::Client client("wss://domain/deepstream");``

**Comment by frobware** [comment]
I started to look at this but I probably need additional context. I modified my config.yaml to include:

```
# SSL Configuration
sslKey: domains/frobware.com.key
sslCert: domains/frobware.com.cert
sslCa: ca.key
```

I was able to start the server. Now when I run the ds-client as:

    $ ./bin/ds-client wss://deepstream:6020/deepstream
    Caught exception "No message received"

I didn't see any connection on the server side.

**Comment by yasserf** [comment]
I think that is because poco doesn't automatically connect when using wss and requires extra data associated.

**Comment by frobware** [comment]
I made some progress today with this but the commits I have are a little jumbled together. I'm going to address the static build first, then look at landing the minimum  changes required to enable wss://.

**Comment by frobware** [comment]
WIP tree - https://github.com/frobware/deepstream.io-client-cpp/tree/connect-over-ssl
